### ISSUE TITLE
关于tcp协议连接弹幕服务器的问题

### ISSUE THREAD

**Issue by simon300000** [EricEcho/BilibiliTool#1]
您好，我是Node.js程序员，目前也写了连接B站直播弹幕服务器的代码，用的是wss协议

> 模式13使用tcp协议(boost asio)连接弹幕服务器，经测试，网络条件允许时，1800个房间没问题。

想问一下这个tcp连接具体是怎么实现的→_→？似乎性能比wss好了很多

**Comment by echo094** [comment]
TCP用的是[Boost.Asio](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio.html)，一个C++库。在windows下应该是IOCP模式，可以在代码文件[boost/asio/impl/io_context.hpp](https://github.com/boostorg/asio/blob/develop/include/boost/asio/impl/io_context.hpp)找到定义`BOOST_ASIO_HAS_IOCP`。
程序里的WebSocket库底层也是用的asio。此外，Node.js在底层实现上应该也是IOCP。
这三者在技术实现上是类似的，性能的差异更可能体现在协议上。

考虑到TCP是传输层协议，WSS是基于TCP的应用层协议，并且WSS还需要加解密，发送同样的数据，TCP的效率一定是更高的。另外，根据协议，WSS建立连接的开销比TCP大很多。**WSS首先需要建立TCP连接，然后需要进行一次基于HTTP协议的握手，才能切换到WSS协议进行通信。**
在测试同时连接1200个房间时，在同样的硬件与系统环境，同样只开1个处理线程的情况下，基于`asio`的TCP能够在不到3s建立所有连接，不到5s完成第一次弹幕协议的收发。但是基于`websocketpp`的WSS协议在5s内只能完成不到220个连接的建立和第一次弹幕协议的收发，随后的连接因为超时被自动关闭了。差距还是很大的。
这虽然有程序本身的因素，但是我觉得在握手阶段，WSS协议比TCP多出的一次HTTP握手也是主要因素。

**Comment by ilharp** [comment]
不得不说tql
我要好好学学
